# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e57bcd3120ea2382ec1b7bd0c06c1465ca85c8bb630197c4c4fee3a053cb9cf716601991181b2fc11d715127aaed46d96d6bdf87d295568c3d5d9346957937b

test:
  secret_key_base: a5a13bb92fd88a03a50e5b4e4377d93727167c91e2f106a4b093268e93e22523e844faa0a2fc9c968cc95bc7ea99212bbca482d4cdeee75e35b8853ac0086a1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
